# Base configs
baseurl: "https://colingore.com"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls-CG"
image_thumbs_loc: "/images/thumbs-CG"
google_analytics: "G-94DB2LYD83"

# UI configs
title: "Photographs and Works on Paper by Colin Gore"
subtitle: "Historic and modern processes"
author: "Colin Gore"
header:
 title: "Photography and more"
 subtitle: "by Colin Gore"
footer:
 name: "My name is Colin"
 bio: "I work primarily with paper and historic photographic processes."

social_urls:
  instagram: "https://www.instagram.com/nero.logic"
  github: "https://www.github.com/ColinGore"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
